server:
    error:
        include-message: "always"
        include-binding-errors: "always"
spring:
    datasource:
        driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
        url: "jdbc:sqlserver://localhost:1433"
        username: "Tirsa"
        password: "ra2KTirsa00sv"
    jpa:
        properties:
            hibernate:
                dialect: "org.hibernate.dialect.SQLServer2012Dialect"
